---
- name: Fetch Instance Info
  os_server_info:
    cloud: "{{ openstack_cloud | default('openstack') }}"
    region_name: regionOne
  register: result
  tags:
    - relinquish

- name: Debug Instances
  debug:
    var: result

# - name: Delete instances
   
