---
- name: Fetch Instance Info
  os_server_info:
    cloud: "{{ openstack_cloud | default('openstack') }}"
  register: instances
  tags:
    - relinquish

- name: Delete instances
  os_server:
    cloud: "{{ openstack_cloud | default('openstack') }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ instances.openstack_servers }}"
  tags:
    - relinquish
