- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_facts:
     cloud: openstack
    register: os_servers
    tags:
      - osp.smoke
    
  - debug:
      var: os_servers

  # - name: Curl website

  # - name: Fail if 'Ansible has done its job' is not in the page content
  #   fail:
  #   when: "'Ansible has done its job' not in webpage.results[0].content"
  #   tags:
  #     - osp.smoke
