---
postgres_rhel7_repo: "https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
postgres_packages:
  - postgresql10 
  - postgresql10-server 
  - postgresql10-contrib 
  - postgresql10-libs
postgres_library: python-psycopg2