---
- name: Provision the servers
  os_server:
    cloud: "{{ openstack_cloud | default('openstack') }}"
    name: "{{ item.value.name }}"
    security_groups: "{{ item.value.security_group | default(omit) }}"
    state: "{{ item.value.state | default('present') }}"
    image: "{{ item.value.image | default('rhel-7.6') }}"
    flavor: "{{ item.value.flavor | default('m2.medium') }}"
    meta: "group={{ item.value.meta[0].group }},deployment_name={{ item.value.meta[0].deployment_name }}"
    nics:
      - net-name: int_network
    userdata: |
      #!/bin/bash
      curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
      curl -o /tmp/openstack.pem http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pem
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
      cat /tmp/openstack.pem >> /home/cloud-user/.ssh/authorized_keys
      sudo curl -o /etc/yum.repos.d/internal.repo http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
  loop: "{{ osp_servers | dict2items }}"
  register: server_instances

- name: Debug server instances
  debug:
    msg: ">> {{ item.item.instance_name }}"
  loop: "{{ server_instances.results }}"

- name: Add floating IP
  os_floating_ip:
    cloud: "{{ openstack_cloud | default('openstack') }}"
    state: present
    reuse: yes
    server: "{{ item.item.name }}"
    network: ext_network
    wait: true
    timeout: 200
  loop: "{{ server_instances.results }} "
