---
- name: Fetch Instance Info
  os_server_info:
    cloud: openstack
  register: result

- name: Display Instance Info
  debug:
    var: item
  loop: "{{result.openstack_servers}}"

- name: Add host by meta data
  add_host:
    name: "{{ item.public_v4 }}"
    group: "{{ item.metadata.group }}"
    ansible_ssh_private_key_file: ~/.ssh/openstack.pem
    ansible_ssh_user: cloud-user
  loop: "{{result.openstack_servers}}"

- name: Add host by deployment name
  add_host:
    name: "{{ item.public_v4 }}"
    group: "{{ item.metadata.deployment_name }}"
    ansible_ssh_private_key_file: ~/.ssh/openstack.pem
    ansible_ssh_user: cloud-user
  loop: "{{result.openstack_servers}}"
