---

- name: Install Postgres packages
  package:
    name: "{{ __package }}"
    state: present
  loop: 
    - "{{ postgres_rhel7_repo }}"        
    - "{{ postgres_packages }}"
    - "{{ postgres_library }}"
  loop_control:
    loop_var: __package

- name: Check if Postgres initialized
  stat:
    path: "{{ postgres_10_data_dir }}/PG_VERSION"
  register: r_postgres_init_dir_state